version: '2.2'
services:
   db:
     image: mysql:5.5
     container_name: localmysqldb
     ports:
       - "3306:3306"
     volumes:
       - test_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: googledb
       MYSQL_USER: googler
       MYSQL_PASSWORD: password
     healthcheck:
       test: "mysql --user=root --password=password --execute \"SHOW DATABASES;\""
       interval: 5s
       timeout: 60s
       retries: 20
volumes:
    test_db_data: