version: '2.2'
services:
  db:
    image: mysql:5.7
    container_name: localmysql
    volumes:
      - localdb_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: itachi
      MYSQL_USER: bhanuchander
      MYSQL_PASSWORD: password
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.001'
          memory: 20M
volumes:
  localdb_data: